/** Ohio SOS county numbers 1–88 → display names (for UI labels). */
export const OHIO_COUNTY_NAME_BY_NUMBER: Record<string, string> = {
  '1': 'Adams',
  '2': 'Allen',
  '3': 'Ashland',
  '4': 'Ashtabula',
  '5': 'Athens',
  '6': 'Auglaize',
  '7': 'Belmont',
  '8': 'Brown',
  '9': 'Butler',
  '10': 'Carroll',
  '11': 'Champaign',
  '12': 'Clark',
  '13': 'Clermont',
  '14': 'Clinton',
  '15': 'Columbiana',
  '16': 'Coshocton',
  '17': 'Crawford',
  '18': 'Cuyahoga',
  '19': 'Darke',
  '20': 'Defiance',
  '21': 'Delaware',
  '22': 'Erie County',
  '23': 'Fairfield',
  '24': 'Fayette',
  '25': 'Franklin',
  '26': 'Fulton',
  '27': 'Gallia',
  '28': 'Geauga',
  '29': 'Greene',
  '30': 'Guernsey',
  '31': 'Hamilton',
  '32': 'Hancock',
  '33': 'Hardin',
  '34': 'Harrison',
  '35': 'Henry',
  '36': 'Highland',
  '37': 'Hocking',
  '38': 'Holmes',
  '39': 'Huron',
  '40': 'Jackson',
  '41': 'Jefferson',
  '42': 'Knox',
  '43': 'Lake',
  '44': 'Lawrence',
  '45': 'Licking',
  '46': 'Logan',
  '47': 'Lorain',
  '48': 'Lucas',
  '49': 'Madison',
  '50': 'Mahoning',
  '51': 'Marion',
  '52': 'Medina',
  '53': 'Meigs',
  '54': 'Mercer',
  '55': 'Miami',
  '56': 'Monroe',
  '57': 'Montgomery',
  '58': 'Morgan',
  '59': 'Morrow',
  '60': 'Muskingum',
  '61': 'Noble',
  '62': 'Ottawa',
  '63': 'Paulding',
  '64': 'Perry',
  '65': 'Pickaway',
  '66': 'Pike',
  '67': 'Portage',
  '68': 'Preble',
  '69': 'Putnam',
  '70': 'Richland',
  '71': 'Ross',
  '72': 'Sandusky',
  '73': 'Scioto',
  '74': 'Seneca',
  '75': 'Shelby',
  '76': 'Stark County',
  '77': 'Summit',
  '78': 'Trumbull',
  '79': 'Tuscarawas',
  '80': 'Union',
  '81': 'Van Wert',
  '82': 'Vinton',
  '83': 'Warren',
  '84': 'Washington',
  '85': 'Wayne',
  '86': 'Williams',
  '87': 'Wood',
  '88': 'Wyandot',
};

export type CountyOption = { number: string; name: string };

/** Sorted list of all SOS county numbers with labels (1–88). */
export function allOhioCountyOptions(): CountyOption[] {
  return Array.from({ length: 88 }, (_, i) => {
    const number = String(i + 1);
    const name = OHIO_COUNTY_NAME_BY_NUMBER[number] ?? `County ${number}`;
    return { number, name };
  });
}
